### ISSUE TITLE
Member add ticket method null pointer

### ISSUE THREAD

**Issue by Shafeman** [Shafeman/BarbarianTheater#5]
As the title says, during a ticket sell, Member.add() currently throws a null pointer exception when trying to add the new ticket into the list. I didn't have time to sort that out before leaving.

**Comment by ghost** [comment]
initialized ticketsBought in Member and changed the price variable in sellTicket() in Theater to an Integer. Not getting a NullPointerEx when buying ticket now... still needs testing,

**Comment by ghost** [comment]
Done some tests and every thing here seems to been in order
