### ISSUE TITLE
Clients Balance is not getting updated

### ISSUE THREAD

**Issue by ghost** [Shafeman/BarbarianTheater#8]
After switching from Integers to BigDecimal it looks like the client has 0 balance after selling tickets. I have just looked it over, could not see anything strait away.

**Comment by kangn** [comment]
Balance fixed
http://stackoverflow.com/questions/1846900/addition-for-bigdecimal
Big decimal is immutable, thus when you called balance.add(amount); this function returns a value of bigDecimal + bigDecimal but doesn't change the balance itself
